-- ============================================
-- ORACLE DDL SCHEMA FOR COUPON MANAGEMENT SYSTEM
-- ============================================

-- Drop existing objects (for clean install)
-- DROP TABLE COUPON CASCADE CONSTRAINTS;
-- DROP TABLE COUPON_BATCH CASCADE CONSTRAINTS;
-- DROP TABLE CAMPAIGN CASCADE CONSTRAINTS;
-- DROP SEQUENCE CAMPAIGN_SEQ;
-- DROP SEQUENCE COUPON_BATCH_SEQ;
-- DROP SEQUENCE COUPON_SEQ;

-- ============================================
-- SEQUENCES
-- ============================================

CREATE SEQUENCE CAMPAIGN_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE COUPON_BATCH_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE COUPON_SEQ
    START WITH 1
    INCREMENT BY 1
    CACHE 1000
    NOCYCLE;

-- ============================================
-- TABLES
-- ============================================

CREATE TABLE CAMPAIGN (
    ID NUMBER(19) DEFAULT CAMPAIGN_SEQ.NEXTVAL PRIMARY KEY,
    NAME VARCHAR2(255) NOT NULL,
    DESCRIPTION VARCHAR2(2000),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
    CONSTRAINT CAMPAIGN_NAME_UK UNIQUE (NAME)
);

COMMENT ON TABLE CAMPAIGN IS 'Stores marketing campaign information';
COMMENT ON COLUMN CAMPAIGN.NAME IS 'Campaign name - must be unique';
COMMENT ON COLUMN CAMPAIGN.ACTIVE IS '1=Active, 0=Inactive (soft delete)';

CREATE TABLE COUPON_BATCH (
    ID NUMBER(19) DEFAULT COUPON_BATCH_SEQ.NEXTVAL PRIMARY KEY,
    CAMPAIGN_ID NUMBER(19) NOT NULL,
    PREFIX VARCHAR2(6) NOT NULL,
    COUPON_COUNT NUMBER(10) NOT NULL,
    POS_CODE VARCHAR2(50),
    ATG_CODE VARCHAR2(50),
    START_DATE DATE NOT NULL,
    EXPIRY_DATE DATE NOT NULL,
    MAX_USAGES NUMBER(10) DEFAULT 1 NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
    CONSTRAINT BATCH_CAMPAIGN_FK FOREIGN KEY (CAMPAIGN_ID) 
        REFERENCES CAMPAIGN(ID) ON DELETE CASCADE,
    CONSTRAINT BATCH_PREFIX_CHK CHECK (PREFIX LIKE 'FF%' AND LENGTH(PREFIX) = 6),
    CONSTRAINT BATCH_DATES_CHK CHECK (EXPIRY_DATE >= START_DATE),
    CONSTRAINT BATCH_COUNT_CHK CHECK (COUPON_COUNT > 0 AND COUPON_COUNT <= 3000000),
    CONSTRAINT BATCH_USAGES_CHK CHECK (MAX_USAGES > 0)
);

COMMENT ON TABLE COUPON_BATCH IS 'Stores batch generation metadata';
COMMENT ON COLUMN COUPON_BATCH.PREFIX IS 'FF + 4 user-defined characters';
COMMENT ON COLUMN COUPON_BATCH.COUPON_COUNT IS 'Number of coupons generated in this batch';
COMMENT ON COLUMN COUPON_BATCH.MAX_USAGES IS 'Maximum number of times each coupon can be redeemed';

CREATE TABLE COUPON (
    ID NUMBER(19) DEFAULT COUPON_SEQ.NEXTVAL PRIMARY KEY,
    BATCH_ID NUMBER(19) NOT NULL,
    CODE VARCHAR2(14) NOT NULL,
    STATUS VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
    USAGE_COUNT NUMBER(10) DEFAULT 0 NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT COUPON_BATCH_FK FOREIGN KEY (BATCH_ID) 
        REFERENCES COUPON_BATCH(ID) ON DELETE CASCADE,
    CONSTRAINT COUPON_STATUS_CHK CHECK (STATUS IN ('ACTIVE', 'INACTIVE', 'EXPIRED', 'MAX_USED')),
    CONSTRAINT COUPON_USAGE_CHK CHECK (USAGE_COUNT >= 0)
);

COMMENT ON TABLE COUPON IS 'Stores individual coupon codes';
COMMENT ON COLUMN COUPON.CODE IS 'Format: FF + 4 chars (prefix) + 8 random chars (A-Z, 0-9)';
COMMENT ON COLUMN COUPON.STATUS IS 'ACTIVE, INACTIVE, EXPIRED, or MAX_USED';
COMMENT ON COLUMN COUPON.USAGE_COUNT IS 'Number of times this coupon has been redeemed';

-- ============================================
-- INDEXES
-- ============================================

-- Global unique index on coupon code (CRITICAL for uniqueness enforcement)
CREATE UNIQUE INDEX COUPON_CODE_UK ON COUPON(CODE);

-- Performance indexes for filtering operations
CREATE INDEX COUPON_BATCH_IDX ON COUPON(BATCH_ID);
CREATE INDEX COUPON_STATUS_IDX ON COUPON(STATUS);
CREATE INDEX COUPON_CREATED_IDX ON COUPON(CREATED_AT);
CREATE INDEX COUPON_CODE_PREFIX_IDX ON COUPON(SUBSTR(CODE, 1, 6));

-- Batch filtering indexes
CREATE INDEX BATCH_CAMPAIGN_IDX ON COUPON_BATCH(CAMPAIGN_ID);
CREATE INDEX BATCH_DATES_IDX ON COUPON_BATCH(START_DATE, EXPIRY_DATE);
CREATE INDEX BATCH_ACTIVE_IDX ON COUPON_BATCH(ACTIVE);

-- Campaign indexes
CREATE INDEX CAMPAIGN_ACTIVE_IDX ON CAMPAIGN(ACTIVE);

-- ============================================
-- TRIGGERS FOR UPDATED_AT
-- ============================================

CREATE OR REPLACE TRIGGER CAMPAIGN_UPDATE_TRG
BEFORE UPDATE ON CAMPAIGN
FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := CURRENT_TIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER BATCH_UPDATE_TRG
BEFORE UPDATE ON COUPON_BATCH
FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := CURRENT_TIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER COUPON_UPDATE_TRG
BEFORE UPDATE ON COUPON
FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := CURRENT_TIMESTAMP;
END;
/
